Global:
  debug: false
  use_gpu: true
  epoch_num: 800
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/ocr/rec
  save_epoch_step: 50
  eval_batch_step: [0, 10]
  cal_metric_during_train: true
  pretrained_model: ./models/ch_PP-OCRv2_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: true
  character_dict_path: ./models/ppocr_keys_v1.txt
  character_type: ch
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true

# Optimizer:
#   name: Adam
#   beta1: 0.9
#   beta2: 0.999
#   lr:
#     name: Cosine
#     learning_rate: 0.001
#   regularizer:
#     name: "L2"
#     factor: 0.00004

# Architecture:
#   model_type: rec
#   algorithm: CRNN
#   Transform:
#   Backbone:
#     name: ResNet
#     layers: 34
#   Neck:
#     name: SequenceEncoder
#     encoder_type: rnn
#     hidden_size: 256
#   Head:
#     name: CTCHead
#     fc_decay: 0.00004

# Loss:
#   name: CTCLoss

# PostProcess:
#   name: CTCLabelDecode

# Metric:
#   name: RecMetric
#   main_indicator: acc
# 模型定义相关配置开始，无需修改
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [700, 800]
    values : [0.001, 0.0001]
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 2.0e-05

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 64
  Head:
    name: CTCHead
    mid_channels: 96
    fc_decay: 0.00002

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
# 模型定义相关配置结束

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/ocr/
    label_file_list:
      - ./data/ocr/train_rec_gt.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RecAug:
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 640]
      - KeepKeys:
          keep_keys: ["image", "label", "length"] 
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/ocr
    label_file_list:
      - ./data/ocr/val_rec_gt.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 640]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 8
